name: Ruby

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [1.8.x, 1.9.x, 2.0.x, 2.1.x, 2.2.x,
          2.3.x, 2.4.x, 2.5.x, 2.6.x, 2.7.x, 3.0.x]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with RSpec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
